name = "The Casket of Reveries "
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0564fb54477b0028f6d1508ffa61c038dbe37863c9d1fd3b443e3847cb2891a"

[versions]
minecraft = "1.20.1"
forge = "47.4.4"
