name = "The Casket of Reveries "
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa7b1deafcb9aa4cac4f945e486952d9b9cc456e4873dfcbaa0eada6b4a7803c"

[versions]
minecraft = "1.20.1"
forge = "47.4.4"
