name = "The Casket of Reveries "
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bee90b5936956c2358df429eea7c3453d63a982e23dd87f910a5396a1671449"

[versions]
minecraft = "1.20.1"
forge = "47.4.4"
