version=1
count=12
file.0.projectId=1622270
file.0.fileId=8647117
file.0.displayName=Apex Hosting Partner Link
file.0.expectedFilename=apexhosting-partner-link-forge-1.20.1-1.0.3.jar
file.0.version=1.0.3
file.0.loader=Forge
file.0.minecraftVersion=[1.20.1,1.20.2)
file.0.browserUrl=https\://www.curseforge.com/minecraft/mc-mods/apex-hosting-partner-link/download/8647117
file.0.sha256=bb882a4e044d34afd0e6cc889cfc8ee1d219ed80bc4cc186953965e11093afe3
file.0.targetPath=mods/apexhosting-partner-link-forge-1.20.1-1.0.3.jar
file.0.size=668727
file.1.projectId=1158208
file.1.fileId=6727019
file.1.displayName=ATi Structures - Vanilla Edition
file.1.expectedFilename=ATi Structures Vanilla V1.4.5.jar
file.1.version=1.4.5
file.1.loader=Fabric
file.1.minecraftVersion=
file.1.browserUrl=https\://www.curseforge.com/minecraft/mc-mods/ati-structures-datapack-vanilla/download/6727019
file.1.sha256=cc64b50e80c03bf5e0abd1c6ba76c87397b972adcf678de87d81d85dd7244098
file.1.targetPath=mods/ATi Structures Vanilla V1.4.5.jar
file.1.size=14745887
file.2.projectId=1401130
file.2.fileId=8621676
file.2.displayName=BetterTridentModel
file.2.expectedFilename=better_trident_model-forge1.20.1-1.2.0.jar
file.2.version=1.2.0
file.2.loader=Forge
file.2.minecraftVersion=[1.20.1,1.21)
file.2.browserUrl=https\://www.curseforge.com/minecraft/mc-mods/bettertridentmodel/download/8621676
file.2.sha256=1777c02a7478b615c34d5f95d172c50f49b65a350cb89972b2af0e313a7a3672
file.2.targetPath=mods/better_trident_model-forge1.20.1-1.2.0.jar
file.2.size=1031045
file.3.projectId=542294
file.3.fileId=7453586
file.3.displayName=BrassAmber BattleTowers
file.3.expectedFilename=ba_bt-1.20.1-3.0.0-beta3.2.1.jar
file.3.version=1.20.1-3.0.0-beta3.2.1
file.3.loader=Forge
file.3.minecraftVersion=[1.20.1,1.21)
file.3.browserUrl=https\://www.curseforge.com/minecraft/mc-mods/brassamberbattletowers/download/7453586
file.3.sha256=df9cbc8b7f657858d1fa823c6eabe1af027e02c0e9b5fdbd5c4398ae97653ed6
file.3.targetPath=mods/ba_bt-1.20.1-3.0.0-beta3.2.1.jar
file.3.size=54453322
file.4.projectId=1023333
file.4.fileId=7699589
file.4.displayName=ChatPlus
file.4.expectedFilename=chatplus-forge-2.8.1.jar
file.4.version=2.8.1
file.4.loader=Forge
file.4.minecraftVersion=[1.20.1,)
file.4.browserUrl=https\://www.curseforge.com/minecraft/mc-mods/chat-plus/download/7699589
file.4.sha256=f30736ebfbeb7f422401e780458ce23b0a9f6e97edef63151fa373becf90ea29
file.4.targetPath=mods/chatplus-forge-2.8.1.jar
file.4.size=27070339
file.5.projectId=448233
file.5.fileId=8287086
file.5.displayName=Entity Culling Fabric/Forge
file.5.expectedFilename=entityculling-forge-1.10.5-mc1.20.1.jar
file.5.version=1.10.5
file.5.loader=Forge
file.5.minecraftVersion=1.20.1
file.5.browserUrl=https\://www.curseforge.com/minecraft/mc-mods/entityculling/download/8287086
file.5.sha256=db0ee6aaf7e78d758885969e1d237e6efef07109195d4bb81fa06b304ddc12aa
file.5.targetPath=mods/entityculling-forge-1.10.5-mc1.20.1.jar
file.5.size=1590221
file.6.projectId=1541678
file.6.fileId=8165247
file.6.displayName=Multiplayer Boss Attribute Modifier
file.6.expectedFilename=multiplayer_boss_fight-forge1.20.1-1.0.3.jar
file.6.version=1.0.3
file.6.loader=Forge
file.6.minecraftVersion=[1.20.1,1.21)
file.6.browserUrl=https\://www.curseforge.com/minecraft/mc-mods/multiplayer-boss-attribute-modifier/download/8165247
file.6.sha256=798d49cb14f03ed0470e77b6a9cdd53df206a71c259b1e0ee70a2f3f1a8ed10d
file.6.targetPath=mods/multiplayer_boss_fight-forge1.20.1-1.0.3.jar
file.6.size=19187
file.7.projectId=550579
file.7.fileId=5929264
file.7.displayName=ServerCore
file.7.expectedFilename=servercore-forge-1.5.2+1.20.1.jar
file.7.version=1.5.2+1.20.1
file.7.loader=Forge
file.7.minecraftVersion=[1.20.1,)
file.7.browserUrl=https\://www.curseforge.com/minecraft/mc-mods/servercore/download/5929264
file.7.sha256=d9ad4f456b6c36bac17a71cd12935fdccae69ca1e1fcd33857210758cb58e586
file.7.targetPath=mods/servercore-forge-1.5.2+1.20.1.jar
file.7.size=1508496
file.8.projectId=1325071
file.8.fileId=8671039
file.8.displayName=TCR Core
file.8.expectedFilename=tcrcore-2.8.7.jar
file.8.version=2.8.7
file.8.loader=Forge
file.8.minecraftVersion=[1.20.1,1.21)
file.8.browserUrl=https\://www.curseforge.com/minecraft/mc-mods/tcr-core/download/8671039
file.8.sha256=9a18c40094c9a61362f8d1870e40e5687ff1c55e27af54c569e7b934eeeb2fd6
file.8.targetPath=mods/tcrcore-2.8.7.jar
file.8.size=39120708
file.9.projectId=1453870
file.9.fileId=7710887
file.9.displayName=TCRMeshes
file.9.expectedFilename=tcrmeshes-1.0.0.jar
file.9.version=1.0.0
file.9.loader=Forge
file.9.minecraftVersion=[1.20.1,1.21)
file.9.browserUrl=https\://www.curseforge.com/minecraft/mc-mods/tcrmeshes/download/7710887
file.9.sha256=2a22f47e917db3414e90ae40429dbd0b74e43fe6ce3788ad27fc565607270609
file.9.targetPath=mods/tcrmeshes-1.0.0.jar
file.9.size=173664
file.10.projectId=1418999
file.10.fileId=7715726
file.10.displayName=Trek
file.10.expectedFilename=trek-B0.6.jar
file.10.version=1-B0.6
file.10.loader=Fabric
file.10.minecraftVersion=
file.10.browserUrl=https\://www.curseforge.com/minecraft/mc-mods/trek-mod/download/7715726
file.10.sha256=78c27ae931278eca9e2fd86e73b08f44ff5962cac4d1a3f701a26c257d6e32ef
file.10.targetPath=mods/trek-B0.6.jar
file.10.size=25458242
file.11.projectId=1359195
file.11.fileId=8066785
file.11.displayName=Vulmoons cataclysm remake
file.11.expectedFilename=Vulmoons calaclysm remake_0.5.zip
file.11.version=0.5
file.11.loader=
file.11.minecraftVersion=
file.11.browserUrl=https\://www.curseforge.com/minecraft/texture-packs/vulmoons-calaclysm-remake/download/8066785
file.11.sha256=c146eff2d40485a04c148d44305b0d16a7413652880dc3f51348c1a05e40904b
file.11.targetPath=resourcepacks/Vulmoons calaclysm remake_0.5.zip
file.11.size=73627
